@startuml
class MainActvity{

 }
 interface CameraBridgeViewBase.CvCameraViewListener2
MainActvity --|>CameraBridgeViewBase.CvCameraViewListener2
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml