@startuml
interface VideoReader {
    static final int  TYPE_HORIZONTAL=361;
    static final int  TYPE_VERCICAL=-361;
    static final int  TYPE_UNKNOW=362;
    static final int  TYPE_360=363;
    int  getSensor(int position);
    Mat getMat(int position);
    int size();
    String getVideoMessage();
    int getType();
    int getLength();
    int  getSensorIndex(int sensor);
    void  readMat(int position, Mat mat);
}

@enduml